export const products = [
    {
        id: 0,
        image: './Assets/images/Airpods.jpg',
        productTitle: "White Airpods",
        price: 10500,
        filterType: "gadget",
    },
    {
        id: 1,
        image: './Assets/images/Black-Bag.jpg',
        productTitle: "Black Bag",
        price: 4500,
        filterType: "bag",
    },
    {
        id: 2,
        image: './Assets/images/Black-Hoodie.jpg',
        productTitle: "Black Alphabet Hoodie",
        price: 8000,
        filterType: "shirt",
    },
    {
        id: 3,
        image: './Assets/images/Black-Jeans.jpg',
        productTitle: "Acne Black Jeans",
        price: 9500,
        filterType: "trouser",
    },
    {
        id: 4,
        image: './Assets/images/Black-School-Bag.jpg',
        productTitle: "Jean Blue Bag",
        price: 10500,
        filterType: "bag",
    },
    {
        id: 5,
        image: './Assets/images/Black-Shirt.jpg',
        productTitle: "Yahew Black Shirt",
        price: 4000,
        filterType: "shirt",
    },
    {
        id: 6,
        image: './Assets/images/Black-Watch.jpg',
        productTitle: "Black Smart Wrist-Watch",
        price: 14000,
        filterType: "gadget",
    },
    {
        id: 7,
        image: './Assets/images/Blue-Bag.jpg',
        productTitle: "Blue DavidJones Bag",
        price: 7000,
        filterType: "bag",
    },
    {
        id: 8,
        image: './Assets/images/Blue-Jeans.jpg',
        productTitle: "Dark Blue Jeans",
        price: 8000,
        filterType: "trouser",
    },
    {
        id: 9,
        image: './Assets/images/Cap-net.jpg',
        productTitle: "Apalanchian Cap",
        price: 3000,
        filterType: "cap",
    },
    {
        id: 10,
        image: './Assets/images/Converse-Allstar.jpg',
        productTitle: "Green Converse AllStar",
        price: 21000,
        filterType: "shoe",
    },
    {
        id: 11,
        image: './Assets/images/Female-Boots.jpg',
        productTitle: "Brown Boots",
        price: 23000,
        filterType: "shoe",
    },
    {
        id: 12,
        image: './Assets/images/Female-heels-Multicolor.jpg',
        productTitle: "Multi-color Female Heels",
        price: 30000,
        filterType: "shoe",
    },
    {
        id: 13,
        image: './Assets/images/Female-Heels.jpg',
        productTitle: "Black Female Heels",
        price: 30000,
        filterType: "shoe",
    },
    {
        id: 14,
        image: './Assets/images/Female-pink.jpg',
        productTitle: "Female Trousers",
        price: 6500,
        filterType: "trouser",
    },
    {
        id: 15,
        image: './Assets/images/Female-red.jpg',
        productTitle: "Red Female Trousers",
        price: 4500,
        filterType: "trouser",
    },
    {
        id: 16,
        image: './Assets/images/Gray-Bag.jpg',
        productTitle: "Grey Shoulder Bag",
        price: 6300,
        filterType: "bag",
    },
    {
        id: 17,
        image: './Assets/images/Green-Cap.jpg',
        productTitle: "Green Tree Cap",
        price: 2100,
        filterType: "cap",
    },
    {
        id: 18,
        image: './Assets/images/Green-Hoodie.jpg',
        productTitle: "Green Hoodie",
        price: 7000,
        filterType: "shirt",
    },
    {
        id: 19,
        image: './Assets/images/Green-Nike.jpg',
        productTitle: "Nike Superreo Sneaker",
        price: 18900,
        filterType: "shoe",
    },
    {
        id: 20,
        image: './Assets/images/Grey-Purse-Bag.jpg',
        productTitle: "Purple Shoulder Bag",
        price: 12600,
        filterType: "bag",
    },
    {
        id: 21,
        image: './Assets/images/Head-Warmer.jpg',
        productTitle: "Orange Head Warmer",
        price: 3200,
        filterType: "cap",
    },
    {
        id: 22,
        image: './Assets/images/Headphone.jpg',
        productTitle: "Black HeadPhone",
        price: 15000,
        filterType: "gadget",
    },
    {
        id: 23,
        image: './Assets/images/Icecream-cone-Cap.jpg',
        productTitle: "Orange Cap",
        price: 2900,
        filterType: "cap",
    },
    {
        id: 24,
        image: './Assets/images/Mini-Camera.jpg',
        productTitle: "Sony Mini-Camera",
        price: 33000,
        filterType: "gadget",
    },
    {
        id: 25,
        image: './Assets/images/Multicolor-Bag.jpg',
        productTitle: "Female Flower Bag",
        price: 31000,
        filterType: "bag",
    },
    {
        id: 26,
        image: './Assets/images/Multicolor-Nike.jpg',
        productTitle: "Nike Air Multi-color",
        price: 28000,
        filterType: "shoe",
    },
    {
        id: 27,
        image: './Assets/images/Multicolor-Trouser.jpg',
        productTitle: "Multi-color Trouser",
        price: 20500,
        filterType: "trouser",
    },
    {
        id: 28,
        image: './Assets/images/Nike-Air.jpg',
        productTitle: "Nike Max",
        price: 28900,
        filterType: "shoe",
    },
    {
        id: 29,
        image: './Assets/images/Orange-Hoodie.jpg',
        productTitle: "Orange Skull Hoodie",
        price: 11500,
        filterType: "shirt",
    },
    {
        id: 30,
        image: './Assets/images/Orange-Shirt.jpg',
        productTitle: "Orange Shirt",
        price: 8500,
        filterType: "shirt",
    },
    {
        id: 31,
        image: './Assets/images/Orange-shirt.jpg',
        productTitle: "Original Shirt",
        price: 5900,
        filterType: "shirt",
    },
    {
        id: 32,
        image: './Assets/images/product1.jpg',
        productTitle: "Black Addidas Shirt",
        price: 7000,
        filterType: "shirt",
    },
    {
        id: 32,
        image: './Assets/images/product2.jpg',
        productTitle: "Black Addidas Airpod",
        price: 3000,
        filterType: "gadget",
    },
    {
        id: 33,
        image: './Assets/images/product3.jpg',
        productTitle: "Hooded Parka",
        price: 13000,
        filterType: "shirt",
    },
    {
        id: 34,
        image: './Assets/images/product4.jpg',
        productTitle: "Addidas Metal Bottle",
        price: 6000,
        filterType: "gadget",
    },
    {
        id: 35,
        image: './Assets/images/product6.jpg',
        productTitle: "Addidas Cap",
        price: 6000,
        filterType: "cap",
    },
    {
        id: 36,
        image: './Assets/images/product7.jpg',
        productTitle: "Brown Addidas Bag",
        price: 11000,
        filterType: "bag",
    },
    {
        id: 37,
        image: './Assets/images/product8.jpg',
        productTitle: "Blue Nike",
        price: 18000,
        filterType: "shoe",
    },
    {
        id: 38,
        image: './Assets/images/Red-Mouse.jpg',
        productTitle: "Wireless Red Mouse",
        price: 4600,
        filterType: "gadget",
    },
    {
        id: 39,
        image: './Assets/images/Red-Nike.jpg',
        productTitle: "Red Nike Sneakers",
        price: 12900,
        filterType: "shoe",
    },
    {
        id: 40,
        image: './Assets/images/Shirt-Tie.jpg',
        productTitle: "Coperate Shirt",
        price: 15000,
        filterType: "shirt",
    },
    {
        id: 41,
        image: './Assets/images/Smart-Watch.jpg',
        productTitle: "Black Smart Watch",
        price: 19900,
        filterType: "gadget",
    },
    {
        id: 42,
        image: './Assets/images/VA-Cap.jpg',
        productTitle: "VA RVCA Cap",
        price: 10000,
        filterType: "cap",
    },
    {
        id: 43,
        image: './Assets/images/Whine-School-Bag.jpg',
        productTitle: "Red Bag",
        price: 9000,
        filterType: "bag",
    },
    {
        id: 44,
        image: './Assets/images/White-cap.jpg',
        productTitle: "White Cap",
        price: 3000,
        filterType: "cap",
    },
    {
        id: 45,
        image: './Assets/images/White-Shirt.jpg',
        productTitle: "White Shirt",
        price: 6000,
        filterType: "shirt",
    },
    {
        id: 46,
        image: './Assets/images/Worthy-Cap.jpg',
        productTitle: "Worthy Cap",
        price: 5500,
        filterType: "cap",
    },

]