export const products = [
    {
        id: 0,
        image: 'https://drive.google.com/uc?export=download&id=1ACadBNHhTJVmshLm5XOMtZfmzK2KwXyu',
        productTitle: "White Airpods",
        price: 10500,
        filterType: "gadget",
    },
    {
        id: 1,
        image: 'https://drive.google.com/uc?export=download&id=11G-xxgms9mnjWG36Sso0PSuyArkpH-99',
        productTitle: "Black Bag",
        price: 4500,
        filterType: "bag",
    },
    {
        id: 2,
        image: 'https://drive.google.com/uc?export=download&id=1PcnYVriVdbgJlRmkF6PZOeknzXXh4jXv',
        productTitle: "Black Alphabet Hoodie",
        price: 8000,
        filterType: "shirt",
    },
    {
        id: 3,
        image: 'https://drive.google.com/uc?export=download&id=1lNUAlkMNj529d2XducVzx1hVzDBPAA8K',
        productTitle: "Acne Black Jeans",
        price: 9500,
        filterType: "trouser",
    },
    {
        id: 4,
        image: 'https://drive.google.com/uc?export=download&id=11Zdh8PpSsTXVNcfM4IoFqJXDx9aRJFwC',
        productTitle: "Jean Blue Bag",
        price: 10500,
        filterType: "bag",
    },
    {
        id: 5,
        image: 'https://drive.google.com/uc?export=download&id=1EUYX2himnC_bx_bnEXKTfYGP2XcBoxYO',
        productTitle: "Yahew Black Shirt",
        price: 4000,
        filterType: "shirt",
    },
    {
        id: 6,
        image: 'https://drive.google.com/uc?export=download&id=1h3g2h9P5A39ItWfsCJqYtcgETNEQbmVq',
        productTitle: "Black Smart Wrist-Watch",
        price: 14000,
        filterType: "gadget",
    },
    {
        id: 7,
        image: 'https://drive.google.com/uc?export=download&id=1D92ZL_1iLAL2FYsek5p6GMDPTmKIYWeL',
        productTitle: "Blue DavidJones Bag",
        price: 7000,
        filterType: "bag",
    },
    {
        id: 8,
        image: 'https://drive.google.com/uc?export=download&id=1L9yQiDmszG9hbv9XhDBr52zN83gxOOa-',
        productTitle: "Dark Blue Jeans",
        price: 8000,
        filterType: "trouser",
    },
    {
        id: 9,
        image: 'https://drive.google.com/uc?export=download&id=1XUHoa9hYKEIkRtvMRVou0yF2b6XeWF3n',
        productTitle: "Apalanchian Cap",
        price: 3000,
        filterType: "cap",
    },
    {
        id: 10,
        image: 'https://drive.google.com/uc?export=download&id=1e0qkxo3zVur87Kbm7GhQVZT2cNB1pKTB',
        productTitle: "Green Converse AllStar",
        price: 21000,
        filterType: "shoe",
    },
    {
        id: 11,
        image: 'https://drive.google.com/uc?export=download&id=1Wiv_ekJ0aC_6hcqSeqSHuhuoGcNk78A3',
        productTitle: "Brown Boots",
        price: 23000,
        filterType: "shoe",
    },
    {
        id: 12,
        image: 'https://drive.google.com/uc?export=download&id=13ApCzzswYyppnj8fAHlicDdd00tpWcTY',
        productTitle: "Multi-color Female Heels",
        price: 30000,
        filterType: "shoe",
    },
    {
        id: 13,
        image: 'https://drive.google.com/uc?export=download&id=1_EfCJrKN_SxX31ID9keir4pibrBmVMSQ',
        productTitle: "Black Female Heels",
        price: 30000,
        filterType: "shoe",
    },
    {
        id: 14,
        image: 'https://drive.google.com/uc?export=download&id=1QO5YS5KtCVbsDohGoEFNVBtUe4hzCb1j',
        productTitle: "Female Trousers",
        price: 6500,
        filterType: "trouser",
    },
    {
        id: 15,
        image: 'https://drive.google.com/uc?export=download&id=1u4jpR22E4IOSNhei4x0W5a-8Ane1xG1F',
        productTitle: "Red Female Trousers",
        price: 4500,
        filterType: "trouser",
    },
    {
        id: 16,
        image: 'https://drive.google.com/uc?export=download&id=10u9jhBL1L1inV3ripjcQc7spgu9uZ33k',
        productTitle: "Grey Shoulder Bag",
        price: 6300,
        filterType: "bag",
    },
    {
        id: 17,
        image: 'https://drive.google.com/uc?export=download&id=16tMcCrDD-bFvVcPzSbCLkYnnEc0i9exE',
        productTitle: "Green Tree Cap",
        price: 2100,
        filterType: "cap",
    },
    {
        id: 18,
        image: 'https://drive.google.com/uc?export=download&id=1gyDvgWr8Z0zfsYIiqr30sRLEQO-rv8P-',
        productTitle: "Green Hoodie",
        price: 7000,
        filterType: "shirt",
    },
    {
        id: 19,
        image: 'https://drive.google.com/uc?export=download&id=1p48FszTH3n3rJAeFZJVYK8Euks_u_a1n',
        productTitle: "Nike Superreo Sneaker",
        price: 18900,
        filterType: "shoe",
    },
    {
        id: 20,
        image: 'https://drive.google.com/uc?export=download&id=16XMgO6_ehgAXJ7xJXmBW06wcjhOS0d1E',
        productTitle: "Purple Shoulder Bag",
        price: 12600,
        filterType: "bag",
    },
    {
        id: 21,
        image: 'https://drive.google.com/uc?export=download&id=103ltCrQI7UHo-Ve2MnX72typ2Sh_mxCk',
        productTitle: "Orange Head Warmer",
        price: 3200,
        filterType: "cap",
    },
    {
        id: 22,
        image: 'https://drive.google.com/uc?export=download&id=1fzf02Kj1vHQbNcLrp3teobnddXXRtfss',
        productTitle: "Black HeadPhone",
        price: 15000,
        filterType: "gadget",
    },
    {
        id: 23,
        image: 'https://drive.google.com/uc?export=download&id=1k8utDU4zwVfGXqr0jNRYm0BUFFsTsbkx',
        productTitle: "Orange Cap",
        price: 2900,
        filterType: "cap",
    },
    {
        id: 24,
        image: 'https://drive.google.com/uc?export=download&id=1wjCMlXSbqtCzZ_jhEOSH_7P6puVB4HMq',
        productTitle: "Sony Mini-Camera",
        price: 33000,
        filterType: "gadget",
    },
    {
        id: 25,
        image: 'https://drive.google.com/uc?export=download&id=1V6lC4HfxV2WCQpTQ2KzAvz4vtqHn2xPg',
        productTitle: "Female Flower Bag",
        price: 31000,
        filterType: "bag",
    },
    {
        id: 26,
        image: 'https://drive.google.com/uc?export=download&id=1gETTk4txoT1e3Bq3evVXp8WvWBDhSAja',
        productTitle: "Nike Air Multi-color",
        price: 28000,
        filterType: "shoe",
    },
    {
        id: 27,
        image: 'https://drive.google.com/uc?export=download&id=1lyKl_Uk0F5dBrx436ep0t_dwzJuMABB8',
        productTitle: "Multi-color Trouser",
        price: 20500,
        filterType: "trouser",
    },
    {
        id: 28,
        image: 'https://drive.google.com/uc?export=download&id=1_M5RJ67Y6uEQi19wS5SGZmwHHbQSfNfU',
        productTitle: "Nike Max",
        price: 28900,
        filterType: "shoe",
    },
    {
        id: 29,
        image: 'https://drive.google.com/uc?export=download&id=1dQsG9OHJwV34_MxfYWRq3smKdeKZey78',
        productTitle: "Orange Skull Hoodie",
        price: 11500,
        filterType: "shirt",
    },
    {
        id: 30,
        image: 'https://drive.google.com/uc?export=download&id=17fDHhHYfL3FiwbBnMQLXsRO8dt2NhgYS',
        productTitle: "Orange Shirt",
        price: 8500,
        filterType: "shirt",
    },
    {
        id: 31,
        image: 'https://drive.google.com/uc?export=download&id=1G_65Rqcz5SWENXgBCirVUmmVC7ABQkC4',
        productTitle: "Original Shirt",
        price: 5900,
        filterType: "shirt",
    },
    {
        id: 32,
        image: './Assets/images/product1.jpg',
        productTitle: "Black Addidas Shirt",
        price: 7000,
        filterType: "shirt",
    },
    {
        id: 32,
        image: './Assets/images/product2.jpg',
        productTitle: "Black Addidas Airpod",
        price: 3000,
        filterType: "gadget",
    },
    {
        id: 33,
        image: './Assets/images/product3.jpg',
        productTitle: "Hooded Parka",
        price: 13000,
        filterType: "shirt",
    },
    {
        id: 34,
        image: './Assets/images/product4.jpg',
        productTitle: "Addidas Metal Bottle",
        price: 6000,
        filterType: "gadget",
    },
    {
        id: 35,
        image: './Assets/images/product6.jpg',
        productTitle: "Addidas Cap",
        price: 6000,
        filterType: "cap",
    },
    {
        id: 36,
        image: './Assets/images/product7.jpg',
        productTitle: "Brown Addidas Bag",
        price: 11000,
        filterType: "bag",
    },
    {
        id: 37,
        image: './Assets/images/product8.jpg',
        productTitle: "Blue Nike",
        price: 18000,
        filterType: "shoe",
    },
    {
        id: 38,
        image: 'https://drive.google.com/uc?export=download&id=1wnWGr__Vdc_dtfTixSac4ZFWorw4e10j',
        productTitle: "Wireless Red Mouse",
        price: 4600,
        filterType: "gadget",
    },
    {
        id: 39,
        image: 'https://drive.google.com/uc?export=download&id=1lkX4ghnLnB3tnnh_RrpZoPp3kOy98dxt',
        productTitle: "Red Nike Sneakers",
        price: 12900,
        filterType: "shoe",
    },
    {
        id: 40,
        image: 'https://drive.google.com/uc?export=download&id=1i47cHYg9Z0s_UOh-wiPp56bjmuuZ_A5B',
        productTitle: "Coperate Shirt",
        price: 15000,
        filterType: "shirt",
    },
    {
        id: 41,
        image: 'https://drive.google.com/uc?export=download&id=11yvw7-Wz-oTPQKmFx9YUG2NGPdC0nhqc',
        productTitle: "Black Smart Watch",
        price: 19900,
        filterType: "gadget",
    },
    {
        id: 42,
        image: 'https://drive.google.com/uc?export=download&id=1osgWDzfn4vNO4yTVdsN4HWOkjGmnCLp7',
        productTitle: "VA RVCA Cap",
        price: 10000,
        filterType: "cap",
    },
    {
        id: 43,
        image: 'https://drive.google.com/uc?export=download&id=1pV_0QDL5bl96GkCrEXG_1wFFk5ao0cxT',
        productTitle: "Red Bag",
        price: 9000,
        filterType: "bag",
    },
    {
        id: 44,
        image: 'https://drive.google.com/uc?export=download&id=19rrAa4PE037b41zvVFvdggR9Ph_tDHXf',
        productTitle: "White Cap",
        price: 3000,
        filterType: "cap",
    },
    {
        id: 45,
        image: 'https://drive.google.com/uc?export=download&id=185z-HWbQ9Dx-9oD-7vI21QL9v8CWILcc',
        productTitle: "White Shirt",
        price: 6000,
        filterType: "shirt",
    },
    {
        id: 46,
        image: 'https://drive.google.com/uc?export=download&id=1rbYOYodV2LtQc_vuV83TVnI5ViCLs64V',
        productTitle: "Worthy Cap",
        price: 5500,
        filterType: "cap",
    },

]